//! Emit the C++ data header: the type table and the construct table as `const`
//! arrays. No entry rows — the `javelin-ext` walk reconstructs them (criterion
//! 4). Strokes are pre-encoded to javelin key masks so the header parses
//! nothing at load.

use std::fmt::Write as _;

use super::super::{Construct, InfType, template_fragments};
use super::{c_escape, stroke_mask};
use crate::error::ExpandError;

/// A generous cap on outline length reported to the engine. The walk itself is
/// unbounded (D8); this only bounds how many strokes the engine offers.
const MAX_OUTLINE_LENGTH: u32 = 24;

/// Render the self-contained C++ data header for `types` and `constructs`.
///
/// # Errors
/// Returns [`ExpandError`] when any stroke fails to encode to a key mask.
pub fn emit_data_header(
    types: &[InfType],
    constructs: &[Construct],
) -> Result<String, ExpandError> {
    let mut out = String::from(PREAMBLE);
    out.push_str(&type_rows(types)?);
    let (arrays, rows) = construct_blocks(constructs)?;
    out.push_str(&arrays);
    out.push_str(&rows);
    let _ = write!(
        out,
        "static const uint32_t MAX_OUTLINE_LENGTH = {MAX_OUTLINE_LENGTH}u;\n\n"
    );
    out.push_str("} // namespace steno_generated\n");
    Ok(out)
}

/// The type table array.
fn type_rows(types: &[InfType]) -> Result<String, ExpandError> {
    let mut out = String::from("static const GenType TYPES[] = {\n");
    for t in types {
        let _ = writeln!(
            out,
            "  {{0x{:06X}u, {}u, \"{}\"}},",
            stroke_mask(&t.stroke)?,
            t.arity,
            c_escape(&t.text),
        );
    }
    let _ = write!(
        out,
        "}};\nstatic const uint32_t TYPE_COUNT = {}u;\n\n",
        types.len()
    );
    Ok(out)
}

/// Build the per-construct backing arrays and the `CONSTRUCTS` table together.
fn construct_blocks(constructs: &[Construct]) -> Result<(String, String), ExpandError> {
    let mut arrays = String::new();
    let mut rows = String::from("static const GenConstruct CONSTRUCTS[] = {\n");
    for (i, c) in constructs.iter().enumerate() {
        arrays.push_str(&construct_arrays(i, c)?);
        rows.push_str(&construct_row(i, c)?);
    }
    let _ = write!(
        rows,
        "}};\nstatic const uint32_t CONSTRUCT_COUNT = {}u;\n\n",
        constructs.len(),
    );
    Ok((arrays, rows))
}

/// The three backing arrays (base masks, surface fragments, fill order) for one
/// construct. An empty base or fill order is elided in favour of `nullptr`.
fn construct_arrays(i: usize, c: &Construct) -> Result<String, ExpandError> {
    let mut out = String::new();
    if !c.base.is_empty() {
        let _ = writeln!(
            out,
            "static const uint32_t c{i}Base[] = {{{}}};",
            base_masks(c)?
        );
    }
    let frags: Vec<String> = template_fragments(&c.template)
        .iter()
        .map(|f| format!("\"{}\"", c_escape(f)))
        .collect();
    let _ = writeln!(
        out,
        "static const char *const c{i}Frags[] = {{{}}};",
        frags.join(", ")
    );
    if !c.fill_order.is_empty() {
        let order: Vec<String> = c.fill_order.iter().map(|k| format!("{k}u")).collect();
        let _ = writeln!(
            out,
            "static const uint8_t c{i}Fill[] = {{{}}};",
            order.join(", ")
        );
    }
    Ok(out)
}

/// The comma-joined base-segment key masks of a construct.
fn base_masks(c: &Construct) -> Result<String, ExpandError> {
    let masks: Result<Vec<String>, _> = c
        .base
        .iter()
        .map(|s| stroke_mask(s).map(|m| format!("0x{m:06X}u")))
        .collect();
    Ok(masks?.join(", "))
}

/// One `CONSTRUCTS[]` row referencing the construct's backing arrays.
fn construct_row(i: usize, c: &Construct) -> Result<String, ExpandError> {
    let base = if c.base.is_empty() {
        "nullptr".to_owned()
    } else {
        format!("c{i}Base")
    };
    let fill = if c.fill_order.is_empty() {
        "nullptr".to_owned()
    } else {
        format!("c{i}Fill")
    };
    let (has_shape, shape_mask) = match &c.shape {
        Some(s) => ("true", stroke_mask(s)?),
        None => ("false", 0),
    };
    Ok(format!(
        "  {{{base}, {}u, {has_shape}, 0x{shape_mask:06X}u, c{i}Frags, {fill}, {}u}},\n",
        c.base.len(),
        c.slots.len(),
    ))
}

/// The fixed head of the data header: guard, include, struct definitions.
const PREAMBLE: &str = "\
//---------------------------------------------------------------------------
// Generated by build-javelin from dict.infinite.steno.
// Do not edit and do not commit: out/ is a build product (see the of-javelin
// brief, D4). One record per @type and one per Pass-A construct; zero rows.
//---------------------------------------------------------------------------
#pragma once
#include <stdint.h>

namespace steno_generated {

struct GenType {
  uint32_t stroke;
  uint32_t arity;
  const char *text; // literal with %t argument markers
};

struct GenConstruct {
  const uint32_t *base;          // baseLength segment masks, or nullptr
  uint32_t baseLength;
  bool hasShape;                 // true for a @fuse construct
  uint32_t shape;                // fuse shape mask (valid iff hasShape)
  const char *const *fragments;  // slotCount + 1 surface fragments
  const uint8_t *fillOrder;      // slotCount slot indices, or nullptr
  uint32_t slotCount;
};

";
