//! Emit the golden test header: for each [sampled](super::sample) stroke
//! sequence, the reference walker's verdict (rendered text and validity). The
//! `javelin-ext` unit test replays the same sequences through the generated
//! dictionary and asserts agreement — the C++-vs-walker half of the D9
//! differential. This header is test input, never consulted by a lookup, so a
//! deep answer string living here does not weaken the data header's anti-cheat.

use std::fmt::Write as _;

use super::super::walk::walk;
use super::sample::sample_sequences;
use super::{super::Construct, super::InfType, c_escape, stroke_mask};
use crate::error::ExpandError;

/// Render the golden header pinning the C++ dictionary to the walker.
///
/// # Errors
/// Returns [`ExpandError`] when a sampled stroke fails to encode to a key mask.
pub fn emit_test_header(
    types: &[InfType],
    constructs: &[Construct],
) -> Result<String, ExpandError> {
    let seqs = sample_sequences(types, constructs);
    let mut arrays = String::new();
    let mut rows = String::from("static const GenGolden GOLDENS[] = {\n");
    for (i, seq) in seqs.iter().enumerate() {
        arrays.push_str(&mask_array(i, seq)?);
        rows.push_str(&golden_row(i, seq, types, constructs));
    }
    let _ = write!(
        rows,
        "}};\nstatic const uint32_t GOLDEN_COUNT = {}u;\n\n",
        seqs.len()
    );
    Ok(format!(
        "{PREAMBLE}{arrays}\n{rows}}} // namespace steno_generated\n"
    ))
}

/// The `uint32_t` stroke-mask array backing one golden.
fn mask_array(i: usize, seq: &[String]) -> Result<String, ExpandError> {
    let masks: Result<Vec<String>, _> = seq
        .iter()
        .map(|s| stroke_mask(s).map(|m| format!("0x{m:06X}u")))
        .collect();
    Ok(format!(
        "static const uint32_t g{i}[] = {{{}}};\n",
        masks?.join(", ")
    ))
}

/// One `GOLDENS[]` row: the walker's text and validity for `seq`. A non-terminal
/// or unmatched sequence is invalid and carries no text.
fn golden_row(i: usize, seq: &[String], types: &[InfType], constructs: &[Construct]) -> String {
    let (text, valid) = match walk(seq, types, constructs) {
        Some(r) if r.terminal => (r.text, true),
        _ => (String::new(), false),
    };
    format!(
        "  {{g{i}, {}u, \"{}\", {valid}}},\n",
        seq.len(),
        c_escape(&text),
    )
}

/// The fixed head of the golden header.
const PREAMBLE: &str = "\
//---------------------------------------------------------------------------
// Generated by build-javelin from dict.infinite.steno.
// Golden vectors from the Rust reference walker; do not edit or commit.
// Each row is a stroke sequence with the walker's rendered text and validity.
//---------------------------------------------------------------------------
#pragma once
#include <stdint.h>

namespace steno_generated {

struct GenGolden {
  const uint32_t *strokes;
  uint32_t length;
  const char *text; // expected definition when valid, else \"\"
  bool valid;       // true iff the walk is a terminal match
};

";
