#!/usr/bin/env bash
# Reject retired identifiers in authored files. When an ADR retires a
# concept it ships with its own grep: this is the no_allow_check pattern
# applied to vocabulary. A retired name is allowed to survive only in the
# history/rationale record (docs/DECISIONS.md, docs/retired/**) and the
# audit docs that describe the retirement — anywhere else (live code,
# --help/`about` text, doc comments, README, CLAUDE.md, SPEC/STATUS,
# prompts, assets) it is a lie the next context reseed would re-poison.
#
# The generated `.context/` tree is excluded: it is regenerated by
# `ctx-scan`, never hand-edited (CLAUDE.md), so a stale term there is a
# freshness problem the reseed fixes, not an authored-source violation.
#
# Enumeration is via `git ls-files` (tracked + untracked-not-ignored),
# NOT a filesystem walk, matching the other scripts/ checks — see
# no_allow_check.sh for the rationale.

set -euo pipefail

ROOT="${1:-.}"
cd "$ROOT"

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo "FAIL: retired_terms_check.sh: '$ROOT' is not a git repository" >&2
    exit 1
fi

# Retired vocabulary. Append here whenever an ADR retires an identifier.
BANNED=(ctx-access init-task end-task served_nodes SPEC.md)

# Paths permitted to mention retired terms: the rationale ledger, retired
# designs kept as history, the audit docs, and this script itself.
is_allowed() {
    case "$1" in
    .context/*) return 0 ;;
    docs/DECISIONS.md) return 0 ;;
    docs/retired/*) return 0 ;;
    docs/AUDIT.md) return 0 ;;
    docs/OPUS_CONTEXT_FRESHNESS_PROMPT.md) return 0 ;;
    scripts/retired_terms_check.sh) return 0 ;;
    template/scripts/retired_terms_check.sh) return 0 ;;
    *) return 1 ;;
    esac
}

mapfile -d '' -t all < <(git ls-files -z --cached --others --exclude-standard)

files=()
for f in "${all[@]}"; do
    is_allowed "$f" || files+=("$f")
done

if [[ ${#files[@]} -eq 0 ]]; then
    exit 0
fi

args=()
for t in "${BANNED[@]}"; do
    args+=(-e "$t")
done

FAIL=0
# `/dev/null` forces grep's multi-file `file:line:` prefix (the `path:line`
# form ctx-verify's parser splits) even when one file remains. Do not
# prefix `$line` with a label before emitting it — `path:line:content` must
# stay the first thing after `FAIL:` or ctx-verify's `split_loc` misreads
# the label itself as the file, and the diagnostic loses its real location.
# The suffix appended after `$line` is safe: `split_loc` only inspects up
# to the first colon plus the digit run after it, so anything appended
# later is free-form message text — this is where the "why banned / what
# to do" guidance belongs, since the matched term alone doesn't explain
# either to an agent that has never read the ADR that retired it.
while IFS= read -r line; do
    echo "FAIL: $line -- retired identifier, see docs/DECISIONS.md for the ADR that retired it; remove/rename this occurrence (retired names may only appear in docs/DECISIONS.md or docs/retired/**)" >&2
    FAIL=1
done < <(grep -nHF "${args[@]}" -- "${files[@]}" /dev/null || true)

exit $FAIL
